---
apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: crowler
spec:                
  selector:         
    matchLabels:
      app: crowler
  replicas: 3        
  template:
    metadata:
      labels:        
        app: crowler
    spec:
      containers:
      - image: 101.53.158.226:5000/crowler:1
        imagePullPolicy: Always
        name: crowler
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: crowler
  name: crowler
spec:
  ports:
  - nodePort: 32223
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: crowler
  type: LoadBalancer
